name: Kavita-Pro CI/CD

on:
  push:
    branches:
      - master # O robô acorda quando fazes push para a master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 📥 Clonar o código-fonte
        uses: actions/checkout@v4

      - name: 🟢 Preparar o Node.js (Para o Front-end)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 🏗️ Compilar o Front-end (Angular)
        run: |
          cd UI/Web
          npm install
          npm run build

      - name: 🟣 Preparar o .NET Core (Para o Backend)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Versão que o Kavita exige

      - name: 🔨 Compilar C# para ARM64
        run: |
          mkdir -p _output
          
          # Procura o arquivo C#, ignorando a pasta node_modules completamente
          ARQUIVO_ALVO=$(find . -type f \( -name "*.sln" -o -name "Kavita.csproj" -o -name "API.csproj" \) | grep -v "node_modules" | head -n 1)
          echo "🎯 Arquivo C# principal encontrado em: $ARQUIVO_ALVO"
          
          # 1. Muda o output para uma pasta chamada "Kavita"
          dotnet publish "$ARQUIVO_ALVO" -c Release -r linux-arm64 --self-contained true -o ./Kavita
          
          # 2. Zipa a pasta inteira (criando a estrutura correta Kavita/Kavita lá dentro)
          tar -czvf _output/kavita-linux-arm64.tar.gz Kavita/

      - name: 🐳 Configurar Emulador Multi-Arquitetura (QEMU)
        uses: docker/setup-qemu-action@v3

      - name: 🐳 Configurar Docker Buildx (Para empacotar em ARM)
        uses: docker/setup-buildx-action@v3

      - name: 🐳 Login no GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Construir e Publicar a Imagem Docker (ARM64)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ghcr.io/eufrauzino/kavita-pro:latest